### ISSUE TITLE
Helm install command failing for same deployment yaml

### ISSUE THREAD

**Issue by arjunsbabu** [microclimate-dev2ops/microclimate-dev2ops.github.io#64]
**Issue type:** Question
**Reported in:** 1.10
**Description of issue:** I am trying deploying deployment in two git branches. One is successful and other is failing. The chart folder is same in both and all files..

**Workaround (if possible):** Recreating  the branch by clonning working one will solve the issue. But like to know the reason 

Error in devops pod

``
```time="2019-05-09T13:50:15Z" level=debug msg="DEBUG: checking Helm certs"
time="2019-05-09T13:50:15Z" level=info msg="Helm certificates detected"
time="2019-05-09T13:50:15Z" level=info msg="Issuing Helm command with arguments `[upgrade --install --wait --namespace myhealthcoach --values chart-845131195/pipeline.yaml dohmhc-98462966-adc0-4701-9dd5-e6401b6c3f9a chart-845131195/chart/dohnodemhc --tls --tls-ca-cert=/msb_helm_sec/ca.pem --tls-cert=/msb_helm_sec/cert.pem --tls-key=/msb_helm_sec/key.pem]`"
time="2019-05-09T13:50:15Z" level=info msg="Release "dohmhc-98462966-adc0-4701-9dd5-e6401b6c3f9a" does not exist. Installing it now.
Error: YAML parse error on dohmhc/templates/deployment.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.replicaCount":interface {}(nil)}
"
time="2019-05-09T13:50:15Z" level=error msg="Error executing `upgrade --install --wait --namespace myhealthcoach --values chart-845131195/pipeline.yaml dohmhc-98462966-adc0-4701-9dd5-e6401b6c3f9a chart-845131195/chart/dohnodemhc`: exit status 1"
time="2019-05-09T13:50:27Z" level=debug msg="In status interval"
`````

**Comment by sishida** [comment]
Thank you for bringing this issue to our attention. The Microclimate team has been notified.

**Comment by arjunsbabu** [comment]
the same deployment.yaml is working for another branch . I can fix the error above . But need to know why its not happening for a different branch 
issue deployment.yaml is as follows 
`````
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-selector"
        version: "current"
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.servicePort }}

`````

values.yaml

`````
# Default values for templateExample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sample
  tag: v0.1.0
  pullPolicy: Always

service:
  name: http
  type: ClusterIP
  servicePort: 80
  targetPort: 3000

resources:
  cpu: 100m
  memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
`````

I have tryed manual helm install command using the above files and it worked.
The fix for the above is to add an "" in values.replicacount. After i have done it another error is coming in the microclimate deploy 

ie 
`````
Error: release dohmhc-1eae8af9-978d-466a-9d67-3880463f6dcd failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Replicas: readUint32: unexpected character: �, error found in #10 byte of ...|eplicas":"{ { .Value|..., bigger context ...|mespace":"dev-myhealthcoach"},"spec":{"replicas":"{ { .Values.replicaCount } }","template":{"metadat|...

`````

The same working in a different branch
